### ISSUE TITLE
Issue creating paths to libraries with _enable_libraries in sandbox.py on Windows 7

### ISSUE THREAD

**Issue by magicalhobo** [GoogleCloudPlatform/python-compat-runtime#102]
The problem appears to be this line:

    library_pattern = os.path.join(os.path.dirname(
      os.path.dirname(google.__file__)), _THIRD_PARTY_LIBRARY_FORMAT_STRING)

For example `C:\\google_appengine` tries to load libraries from `C:\\lib\\yaml-3.10` instead of `C:\\google_appengine\\lib\yaml-3.10`.

I'm using 64-bit Python 2.7.7 on Windows 7.

**Comment by bryanmau1** [comment]
Hi, I believe this is actually a devappserver issue as opposed to a python-compat issue.  Could you file a bug in the public issue tracker?

https://code.google.com/p/googleappengine/issues/list

**Comment by jonparrott** [comment]
Also, this particular bug has been fixed and will be in the next SDK release (1.9.40).
