### ISSUE TITLE
INSERT fails with '#' in ID

### ISSUE THREAD

**Issue by tmst** [GoogleCloudPlatform/python-compat-runtime#103]
The `match()` call in the method `lookup_rest_method(self, path, http_method)` in  `api_config_manager.py` always returns `False` when `#` is used as the ID in the API Explorer.

**Comment by jonparrott** [comment]
Can you give me a few more details? Is this an issue related to cloud
endpoints?

**Comment by tmst** [comment]
Maybe. Not sure what else would be helpful. Here's the code block:

def lookup_rest_method(self, path, http_method):
  """Look up the rest method at call time.

  The method is looked up in self._rest_methods, the list it is saved
  in for SaveRestMethod.

  Args:
    path: A string containing the path from the URL of the request.
    http_method: A string containing HTTP method of the request.

  Returns:
    Tuple of (<method name>, <method>, <params>)
    Where:
      <method name> is the string name of the method that was matched.
      <method> is the descriptor as specified in the API configuration. -and-
      <params> is a dict of path parameters matched in the rest request.
  """
  with self._config_lock:
    for compiled_path_pattern, unused_path, methods in self._rest_methods:
      match = compiled_path_pattern.match(path)
      if match:
        params = self._get_path_params(match)
        method_key = http_method.lower()
        method_name, method = methods.get(method_key, (None, None))
        if method:
          break
      else:
        logging.warn('No endpoint found for path: %s', path)
        method_name = None
        method = None
        params = None
    return method_name, method, params

**Comment by jonparrott** [comment]
Okay, so this code is part of cloud endpoints. Unfortunately, the compat
runtime does not currently support cloud endpoints.

**Comment by tmst** [comment]
Sorry about that. I'll post this over there. Yes?

**Comment by jonparrott** [comment]
No worries. :) Good luck!
