### ISSUE TITLE
Should load appengine_config before any handlers (breaks `vendor.add`)

### ISSUE THREAD

**Issue by evanj** [GoogleCloudPlatform/python-compat-runtime#108]
The Standard Environment documents `appengine_config.py` as being a way to change sys.path, for example by using the `vendor` module that is supplied with App Engine. That works on Standard, but does not work with `python-compat`. The reason is that `wsgi_config.py` attempts to load the script, before it loads `appengine_config.py`. The workaround is to `import appengine_config` as the first line of your first handler listed in the .yaml file.

Given that this library is officially deprecated and there is a workaround, I suspect this is not worth fixing, but someone else might find this useful.

The actual problem:

1. `wsgi_config.app_for_script` calls  `wsgi.LoadObject` on the handler from the `.yaml` file: https://github.com/GoogleCloudPlatform/python-compat-runtime/blob/master/appengine-vmruntime/vmruntime/wsgi_config.py#L55
2. If that does not throw an exception, then it calls `app_wrapped_in_user_middleware` which calls `get_add_middleware_from_appengine_config` which actually imports `appengine_config`.

If `appengine_config` calls `vendor.add('lib')` to change `sys.path`, and the handler script depends on that, it will fail.

An alternative workaround: Set `env_variables: PYTHONPATH: 'lib'` in the `.yaml` file.

**Comment by jonparrott** [comment]
Thanks for the report. I'll see if @duggelz deems this worth fixing. Since there are workarounds, it is probably unlikely.

**Comment by duggelz** [comment]
Unfortunately, this is a WONTFIX due to the reasons Jon described.
