### ISSUE TITLE
dev_appserver is failing because gcd_application is removed

### ISSUE THREAD

**Issue by matzika** [GoogleCloudPlatform/python-compat-runtime#109]
`dev_appserver2.py` is not updated to not import gcd_application and as a result running `dev_appserver` fails.

**Comment by duggelz** [comment]
Can you provide the exact command you're running, and the exact error message(s) you see?

**Comment by matzika** [comment]
This is the error I am getting after I updated to the latest version: 
```
Traceback (most recent call last):
  File "/Users/206850/Downloads/google-cloud-sdk/platform/google_appengine/dev_appserver.py", line 101, in <module>
    _run_file(__file__, globals())
  File "/Users/206850/Downloads/google-cloud-sdk/platform/google_appengine/dev_appserver.py", line 97, in _run_file
    execfile(_PATHS.script_file(script_name), globals_)
  File "/usr/local/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 38, in <module>
    from google.appengine.tools.devappserver2 import gcd_application
ImportError: cannot import name gcd_application```

**Comment by duggelz** [comment]
From the traceback, it looks like you are talking about the Google Cloud SDK, and are running the dev_appserver from it on your local machine.

If this is correct, you'll want to file a bug with the Cloud SDK at https://code.google.com/p/google-cloud-sdk/issues/list

Please include the following information:

1) What is the platform and operating system you are running on?  E.g OS X 10.2.3
2) What version of the Cloud SDK are you using?  Run "gcloud info" and paste the result in.
3) What is the exact command line you are using to invoke dev_appserver
4) What are your $PATH and $PYTHONPATH environment variables set to

Also, I don't work on dev_appserver, but it seems suspicious that code from the Google Cloud SDK in /Users/xxxxx/Downloads/google-cloud-sdk is calling code from the AppEngine SDK in /usr/local/google_appengine .  Try removing or renaming /usr/local/google_appengine to something else and see if that alters things.

**Comment by matzika** [comment]
Great thank you!Will do.
