### ISSUE TITLE
Python's skip_files_re in mtime-watcher doesn't work properly

### ISSUE THREAD

**Issue by mikelambert** [GoogleCloudPlatform/python-compat-runtime#110]
I was excited to see the addition of `set_skip_files_re()`, which "Allows the file watcher to respect skip_files in app.yaml."

This is an example from my app.yaml, where the `^` matches relative to the root of the project:
```
skip_files:
- ^node_modules(/.*)?
```

Unfortunately, skip_files_re operates on the full paths in `skip_files_re.match(os.path.join(dirpath, dirname))`, and so fails to match on paths like:
`/Users/myuser/Projects/myproject/node_modules/some-module`

(I'd be happy to submit a pull request to fix this, but AFAIK I cannot find where this code exists besides `python-compat-runtime/appengine-compat/exported_appengine_sdk`. Is there a proper github repo to submit pull requests against?)

**Comment by duggelz** [comment]
The SDK code lives in a private internal repository, and we have to manually copy it to this and other repositories.  We have plans to improve this, but it will take some time.  Meanwhile, it looks like you've already found https://code.google.com/p/googleappengine/issues/detail?id=9300 and the bug has also been reported on our internal issue tracker.

**Comment by mikelambert** [comment]
Thanks for the status update, appreciate it!
