### ISSUE TITLE
Should this repo be marked as deprecated in the README (alongside a pointer to the official docs that list the EOL timeframe)

### ISSUE THREAD

**Issue by mikelambert** [GoogleCloudPlatform/python-compat-runtime#115]

**Comment by duggelz** [comment]
It actually does say "This runtime is currently deprecated." in the README, but clearly it should be more obvious.  And I will add a link to the schedule.

**Comment by duggelz** [comment]
I added DEPRECATED in various places.  The exact timeline for EOL is fluid, please contact Google Support if you have particular concerns or need time extensions.
