### ISSUE TITLE
Cannot use deferred tasks with python-compat on AppEngine Flex

### ISSUE THREAD

**Issue by csilvers** [GoogleCloudPlatform/python-compat-runtime#121]
We're trying to migrate our service to AppEngine Flex but still use the python-compat library.  Using the migration guide things mostly work, but one problem is that deferred tasks no longer work.  The problem is this code in the appengine SDK (ext/deferred.py):
```
    if in_prod and self.request.environ.get("REMOTE_ADDR") != "0.1.0.2":
      logging.error("Detected an attempted XSRF attack. This request did "
                    "not originate from Task Queue.")
      self.response.set_status(403)
```

On AppEngine Flex, the remote address for taskqueues appears to be 172.17.something, not 0.1.0.2.

One solution would be to fix this code to accept "172.17.x.x" (or indeed any private-network IP address) as well as 0.1.0.2.  Another would be to get rid of this check entirely.  (There's a check above it that looks for a particular custom header, which is enough to foil XSRF; this additional check doesn't add any value that I can see.)

But that would require changing the SDK and then folding that change here into python-compat.  There may be a better way to fix things in python-compat, maybe by faking REMOTE_ADDR when it's 172.17.something so it looks like 0.1.0.2 instead?

**Comment by duggelz** [comment]
CC @andrewsg @jonparrott

**Comment by duggelz** [comment]
I will try to figure out the right behavior and update the SDK.

**Comment by csilvers** [comment]
So, we meet again!

Just in case it's helpful: My co-worker is insistent we can just get rid of the check entirely.  His reasoning is that x-appengine-taskname is a "protected" header (google strips it off at the load-balancer) meaning that it cannot exist if there's an xsrf -- or any other kind -- of attack.  So the check above this one, for the existence of that header, is sufficient, and checking the source IP adds no extra value.

**Comment by jonparrott** [comment]
I believe that assessment is correct. Hopefully we can get this resolved. :)

**Comment by duggelz** [comment]
I'm talking to the Cloud Tasks team, and there's some possibility that the header name might change, but they agree checking just the header should be enough.  However, they are surprised that the request is not coming from 0.1.0.2.  Stay tuned.

**Comment by csilvers** [comment]
Luckily, I have the full environment handy, if that helps.  This is the environment when the taskqueue is run.  I scheduled the task like so: `deferred.defer(log_env, _target=target, _queue='backups', _url='/env')`, where `/env` is a route that just logs the environment (so `log_env` is ignored).
```
{
  "headers": {
    "Content-Length": "26", 
    "Content-Type": "application/octet-stream", 
    "Host": "0.flex-python-compat.flextest.khan-academy.appspot.com", 
    "Referer": "http://0.flex-python-compat.flextest.khan-academy.appspot.com/_ah/background", 
    "User-Agent": "AppEngine-Google; (+http://code.google.com/appengine)", 
    "Via": "1.1 google", 
    "X-Appengine-Apphosting-Gfe": "true", 
    "X-Appengine-Country": "ZZ", 
    "X-Appengine-Queuename": "backups", 
    "X-Appengine-Tasketa": "1501022111.8350039", 
    "X-Appengine-Taskexecutioncount": "0", 
    "X-Appengine-Taskname": "70086407221894099811", 
    "X-Appengine-Taskretrycount": "0", 
    "X-Cloud-Trace-Context": "70532ec6d135f0287926c105c29a2074/10428543676009040733", 
    "X-Forwarded-For": "10.0.0.1, 10.0.0.1, 35.190.10.176, 130.211.2.118", 
    "X-Forwarded-Proto": "http", 
    "X-Google-Real-Ip": "130.211.2.118", 
    "X-Real-Ip": "130.211.2.118"
  }, 
  "os_environ": {
    "APPENGINE_LOADBALANCER": "", 
    "APPENGINE_LOADBALANCER_IP": "", 
    "APPENGINE_RUNTIME": "python27", 
    "APPLICATION_ID": "s~khan-academy", 
    "AUTH_DOMAIN": "gmail.com", 
    "BACKEND_ID": "flex-python-compat", 
    "CONTENT_LENGTH": "26", 
    "CONTENT_TYPE": "application/octet-stream", 
    "CURRENT_MODULE_ID": "flextest", 
    "CURRENT_VERSION_ID": "flex-python-compat.402927462211169007", 
    "DATACENTER": "", 
    "DEBIAN_FRONTEND": "noninteractive", 
    "DEFAULT_TICKET": "khan-academy/flextest.flex-python-compat.0", 
    "DEFAULT_VERSION_HOSTNAME": "", 
    "GAE_AFFINITY": "false", 
    "GAE_APPENGINE_HOSTNAME": "khan-academy.appspot.com", 
    "GAE_DEPLOYMENT_ID": "402927462211169007", 
    "GAE_INSTANCE": "aef-flextest-flex--python--compat-j3dg", 
    "GAE_LONG_APP_ID": "khan-academy", 
    "GAE_MEMCACHE_HOST": "memcache", 
    "GAE_MEMCACHE_PORT": "11211", 
    "GAE_MEMORY_MB": "614", 
    "GAE_MINOR_VERSION": "402927462211169007", 
    "GAE_MODULE_INSTANCE": "0", 
    "GAE_MODULE_NAME": "flextest", 
    "GAE_MODULE_VERSION": "flex-python-compat", 
    "GAE_PARTITION": "s", 
    "GAE_SERVICE": "flextest", 
    "GAE_VERSION": "flex-python-compat", 
    "GAE_VM": "true", 
    "GCLOUD_PROJECT": "khan-academy", 
    "GOOGLE_CLOUD_PROJECT": "khan-academy", 
    "HOME": "/root", 
    "HOSTNAME": "d1bd2f5dfde2", 
    "HTTPS": "", 
    "HTTP_HOST": "0.flex-python-compat.flextest.khan-academy.appspot.com", 
    "HTTP_REFERER": "http://0.flex-python-compat.flextest.khan-academy.appspot.com/_ah/background", 
    "HTTP_USER_AGENT": "AppEngine-Google; (+http://code.google.com/appengine)", 
    "HTTP_VIA": "1.1 google", 
    "HTTP_X_APPENGINE_APPHOSTING_GFE": "true", 
    "HTTP_X_APPENGINE_COUNTRY": "ZZ", 
    "HTTP_X_APPENGINE_QUEUENAME": "backups", 
    "HTTP_X_APPENGINE_TASKETA": "1501022111.8350039", 
    "HTTP_X_APPENGINE_TASKEXECUTIONCOUNT": "0", 
    "HTTP_X_APPENGINE_TASKNAME": "70086407221894099811", 
    "HTTP_X_APPENGINE_TASKRETRYCOUNT": "0", 
    "HTTP_X_CLOUD_TRACE_CONTEXT": "70532ec6d135f0287926c105c29a2074/10428543676009040733", 
    "HTTP_X_FORWARDED_FOR": "10.0.0.1, 10.0.0.1, 35.190.10.176, 130.211.2.118", 
    "HTTP_X_FORWARDED_PROTO": "http", 
    "HTTP_X_GOOGLE_REAL_IP": "130.211.2.118", 
    "HTTP_X_REAL_IP": "130.211.2.118", 
    "INSTANCE_ID": "0", 
    "LANG": "C.UTF-8", 
    "MEMCACHE_PORT": "tcp://172.17.0.1:11211", 
    "MEMCACHE_PORT_11211_TCP": "tcp://172.17.0.1:11211", 
    "MEMCACHE_PORT_11211_TCP_ADDR": "172.17.0.1", 
    "MEMCACHE_PORT_11211_TCP_PORT": "11211", 
    "MEMCACHE_PORT_11211_TCP_PROTO": "tcp", 
    "MODULE_YAML_PATH": "flex-python-compat.yaml", 
    "PATH": "/env/bin:/opt/python3.5/bin:/opt/python3.6/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin", 
    "PATH_INFO": "/env", 
    "PORT": "8080", 
    "PYTHONUNBUFFERED": "1", 
    "QUERY_STRING": "", 
    "RAW_URI": "/env", 
    "REMOTE_ADDR": "172.17.0.1", 
    "REMOTE_PORT": "59056", 
    "REQUEST_ID_HASH": "", 
    "REQUEST_LOG_ID": "", 
    "REQUEST_METHOD": "POST", 
    "SCRIPT_NAME": "", 
    "SERVER_NAME": "0.flex-python-compat.flextest.khan-academy.appspot.com", 
    "SERVER_PORT": "80", 
    "SERVER_PROTOCOL": "HTTP/1.1", 
    "SERVER_SOFTWARE": "Google App Engine/0.70", 
    "USER_EMAIL": "", 
    "USER_ID": "", 
    "USER_IS_ADMIN": "0", 
    "USER_NICKNAME": "", 
    "USER_ORGANIZATION": "", 
    "USE_MVM_AGENT": "false", 
    "VIRTUAL_ENV": "/env", 
    "WSGI_SERVER_SOFTWARE": "gunicorn/19.6.0", 
    "wsgi.url_scheme": "http"
  }, 
  "sys.path": [
    "/home/vmagent/app", 
    "/env/bin", 
    "/env/lib/python2.7", 
    "/env/lib/python2.7/plat-x86_64-linux-gnu", 
    "/env/lib/python2.7/lib-tk", 
    "/env/lib/python2.7/lib-old", 
    "/env/lib/python2.7/lib-dynload", 
    "/usr/lib/python2.7", 
    "/usr/lib/python2.7/plat-x86_64-linux-gnu", 
    "/usr/lib/python2.7/lib-tk", 
    "/env/local/lib/python2.7/site-packages", 
    "/env/lib/python2.7/site-packages"
  ], 
  "wsgi_environ": {
    "CONTENT_LENGTH": "26", 
    "CONTENT_TYPE": "application/octet-stream", 
    "HTTP_HOST": "0.flex-python-compat.flextest.khan-academy.appspot.com", 
    "HTTP_REFERER": "http://0.flex-python-compat.flextest.khan-academy.appspot.com/_ah/background", 
    "HTTP_USER_AGENT": "AppEngine-Google; (+http://code.google.com/appengine)", 
    "HTTP_VIA": "1.1 google", 
    "HTTP_X_APPENGINE_APPHOSTING_GFE": "true", 
    "HTTP_X_APPENGINE_COUNTRY": "ZZ", 
    "HTTP_X_APPENGINE_QUEUENAME": "backups", 
    "HTTP_X_APPENGINE_TASKETA": "1501022111.8350039", 
    "HTTP_X_APPENGINE_TASKEXECUTIONCOUNT": "0", 
    "HTTP_X_APPENGINE_TASKNAME": "70086407221894099811", 
    "HTTP_X_APPENGINE_TASKRETRYCOUNT": "0", 
    "HTTP_X_CLOUD_TRACE_CONTEXT": "70532ec6d135f0287926c105c29a2074/10428543676009040733", 
    "HTTP_X_FORWARDED_FOR": "10.0.0.1, 10.0.0.1, 35.190.10.176, 130.211.2.118", 
    "HTTP_X_FORWARDED_PROTO": "http", 
    "HTTP_X_GOOGLE_REAL_IP": "130.211.2.118", 
    "HTTP_X_REAL_IP": "130.211.2.118", 
    "PATH_INFO": "/env", 
    "QUERY_STRING": "", 
    "RAW_URI": "/env", 
    "REMOTE_ADDR": "172.17.0.1", 
    "REMOTE_PORT": "59056", 
    "REQUEST_METHOD": "POST", 
    "SCRIPT_NAME": "", 
    "SERVER_NAME": "0.0.0.0", 
    "SERVER_PORT": "8080", 
    "SERVER_PROTOCOL": "HTTP/1.1", 
    "SERVER_SOFTWARE": "gunicorn/19.6.0", 
    "gunicorn.socket": "object of type <class 'socket._socketobject'>", 
    "werkzeug.request": "object of type <class 'flask.wrappers.Request'>", 
    "wsgi.errors": "object of type <class 'gunicorn.http.wsgi.WSGIErrorsWrapper'>", 
    "wsgi.file_wrapper": "object of type <type 'type'>", 
    "wsgi.input": "object of type <class 'gunicorn.http.body.Body'>", 
    "wsgi.multiprocess": false, 
    "wsgi.multithread": true, 
    "wsgi.run_once": false, 
    "wsgi.url_scheme": "http", 
    "wsgi.version": "object of type <type 'tuple'>"
  }
}
```

**Comment by duggelz** [comment]
I'm sorry to say that I have bad news.  Based on discussion and a security review, it was determined that in some configurations of the Flex networking environment, 1) just checking headers is not enough, and 2) IP address checks can not definitively distinguish between Task Queue backends and other hosts and/or containers in every case.  Based on that, and the risk of arbitrary code execution, the policy is: "Deferred Tasks do not function in Flex at all".  You will need to rewrite your deferred task functionality in some other way, port your application back to Standard, or wait for Cloud Tasks to become available.

The long term plan is for Cloud Tasks to use service accounts and credential checking instead of checking HTTP headers and IP address.  Meanwhile, we will update the documentation, and try to emit better error messages.

Again, I am very sorry.

**Comment by csilvers** [comment]
Is "some configurations of the flex networking environment" something that we can control?, to make sure we're in a safe environment?

It sounds like the same risk of unauthenticated requests applies to all task queue tasks, not just deferred tasks.  And you're just calling out deferred tasks specially because the deferred-task endpoint can execute arbitrary code.  Is that right?

We can add our own authentication (using a shared secret) for all our task queues and deferred tasks, so I think we can work around this problem for now.  Since that will require that we write our own handler for deferred tasks anyway, I think this obviates the need to fix this bug, at least until cloud tasks are better supported.

**Comment by csilvers** [comment]
Also -- and I know you are maybe not the authoratative guide on this -- does this mean that we can't trust the X-Appengine-Taskname (or X-Appengine-queuename) header on flex?

**Comment by jonparrott** [comment]
@csilvers it's definitely possible for you to "fork" deferred into your application source and modify it as needed. The chief security concern is that without the IP check a XSS attack could trick someone who is logged in as an admin into arbitrary code execution.

**Comment by csilvers** [comment]
@jonparrott thanks for the explanation of the concern.  This concern is only an issue if there's some way for an admin to execute code with the X-Appengine-Taskname header set.  We had thought -- the documentation said -- that this is impossible, the header will be stripped by the loadbalancer except for actual taskqueue requests.  Hence my worry what we can trust about that header!

**Comment by csilvers** [comment]
(Or maybe the issue is that x-appengine-taskname isn't stripped for admins, or something like that?)

**Comment by jonparrott** [comment]
Right, admins can send X-AppEngine headers.
