### ISSUE TITLE
Diff from Standard: Accessing django.conf.settings at import time changes timezone

### ISSUE THREAD

**Issue by evanj** [GoogleCloudPlatform/python-compat-runtime#70]
If you access django.conf.settings at import time on Managed VMs it changes the timezone to America/Chicago. It does not do this on the Standard environment (see example program below). This is actually "expected" behaviour for Django, but it *is* a difference between the two environments that caused a bug for us that we didn't catch until we tried putting our GCE module in production.

The reason this happens: `django.conf.__init__` calls `time.tzset` to set the timezone to the value in `django.conf.global_settings.TIME_ZONE`, which defaults to `TIME_ZONE = 'America/Chicago'`! You have to do this at module import time, because after imports `os.environ` is monkey patched by `wsgi.py`.

Interesting note: the same code is in `google.appengine._internal.django.conf`, but I was not able to trigger this by importing the things that may depend on it, e.g. through `google.appengine.ext.webapp.template`. Maybe there is some way to trigger this bug through those dependencies, but I wasn't able to reproduce it.

Suggestions:

* It might be worth changing the TIME_ZONE value of the included version of Django to UTC to ensure this can't happen by accidentally importing some `google.appengine.ext` module?

* This may just need to be a documented difference, although if time.tzset really doesn't work on the Standard environment, maybe it should be monkey patched in wsgi.py to do nothing, as a "compatibility" hack? If a user doesn't want this behaviour, they can choose not to use `python-compat`?

Example program that demonstrates this bug. On a Managed VM, the value for datetime.now() and datetime.utcnow() are different.

```
import datetime
import logging
import os
import sys
import time

from django.conf import settings
import webapp2

print "### WTF", settings.FOOBAR

class HelloWebapp2(webapp2.RequestHandler):
  def get(self):
    self.response.headers["Content-Type"] = "text/plain;encoding=UTF-8"
    self.response.write('settings.TIME_ZONE = %s\n' % (repr(settings.TIME_ZONE)))
    self.response.write('datetime.now = %s\n' % (repr(datetime.datetime.now())))
    self.response.write('datetime.utcnow = %s\n' % (repr(datetime.datetime.utcnow())))
    self.response.write('os.environ["TZ"] = %s\n' % (os.environ.get("TZ", "(not set)")))
    self.response.write('time.timezone = %s\n' % (time.timezone))
    self.response.write('time.tzname = %s\n' % (repr(time.tzname)))
    self.response.write('django dir(settings) = %s\n' % (repr(dir(settings))))
    self.response.write('django settings.USE_TZ = %s\n' % (repr(settings.USE_TZ)))
    self.response.write('django settings.TIME_ZONE = %s\n' % (repr(settings.TIME_ZONE)))

app = webapp2.WSGIApplication([
  ('/', HelloWebapp2),
], debug=True)
```

**Comment by jonparrott** [comment]
This is a known issue; MVMs defaults the system timezone to the region
they're in. This issue has been acknowledged internally and I'll keep this
bug updated.

In the meantime it's always a good idea to use utcnow. Depending on the
system timezone is almost never a good idea.

**Comment by evanj** [comment]
Actually, it appears that our MVMs default to UTC:

evan_jones@gae-integration--track--gce-20160329t180647-9qyf:~$ cat /etc/timezone && echo
UTC

Despite the fact they are running in us-central-1. When I run the app above and comment out the "from django.conf import settings" line, my program is running in the expected UTC time zone.

**Comment by evanj** [comment]
I don't disagree with your utcnow() comment. I'm about to change every instance in our program ...

**Comment by jonparrott** [comment]
Then it seems weird that importing something would change your system timezone? I'm not familiar enough with django. @waprin, any ideas here?

**Comment by evanj** [comment]
The "embedded" version of Django in this repo includes the code (see link below). Luckily, this version seems to have been modified so nothing references the Settings object, so you can't get this behavior by just importing webapp. However, in the "real" copy of Django, this object gets instantiated on import. I agree this is totally crazy, but since "time.tzset" does nothing on AppEngine, this did cause bugs for us since we rely on Django components. See:

https://github.com/GoogleCloudPlatform/appengine-python-vm-runtime/blob/2791292e0abeeeefda4ba8c37d36491be887cd84/appengine-compat/exported_appengine_sdk/google/appengine/_internal/django/conf/__init__.py#L46

The actual Django code can be viewed here:

https://github.com/django/django/blob/stable/1.4.x/django/conf/__init__.py#L82


A workaround would be to "freeze" os.environ *before* importing the user code.

**Comment by jonparrott** [comment]
A few things here coming to light:

1. Python standard does bad things.
2. We're not doing the bad thing python standard does.
3. We don't really want users to use the embedded version of django here, it'd be preferable for them to install their django version explicitly with requirements.txt.
4. We don't want to freeze `os.environ`, as it'll probably cause all kinds of weird issues and we'd be trading one deviating behavior for another.

So it seems the *desired* behavior is to somehow make django ignore what's in your `settings.py`? Would it be better for us to just document this weirdness?

**Comment by evanj** [comment]
We fixed it by setting TIME_ZONE="UTC" in our settings module. According to the Django documentation, we should have done this from the beginning, but of course in the AppEngine Standard environment, this doesn't take effect, but it does in the Flexible environment.

I think documenting this as a difference would be fine, particularly since I expect many people will add `django` to `requirements.txt` and may be surprised by this difference. The following page would be a great place to list it. There is a sentence "note that flexible environment differ from Compute Engine VMs in the following ways" with bullet points, you could add something like:

* In the Standard Environment, system APIs like `time.tzset` do not work, but they do work in the Flexible environment. This means third-party libraries you import may make changes to your environment. For example, Django will change your time zone to the value in your settings module (by default changing it to "America/Chicago"). .

https://cloud.google.com/appengine/docs/flexible/python/migrating-an-existing-app

Thanks!

**Comment by jonparrott** [comment]
Perfect, thank you. I'll update that page shortly. Thank you so much for all your help.
