### ISSUE TITLE
SEC: app should not run as root

### ISSUE THREAD

**Issue by westurner** [GoogleCloudPlatform/python-compat-runtime#85]
[gunicorn, app abc] should not be run as root (even in a container).

* https://en.wikipedia.org/wiki/Principle_of_least_privilege
* :CWE-250: Execution with Unnecessary Privileges" https://cwe.mitre.org/data/definitions/250.html

From https://docs.docker.com/engine/security/security/ :

> "Docker containers are, by default, quite secure; especially if you take care of running your processes inside the containers as non-privileged users (i.e., non-root)."

You can fix this by adding the following line before running the process that requires sockets above 1024:

```
USER nonroot
```

* https://github.com/schemaorg/schemaorg/pull/1007/files#diff-d3d258ac6e0a80b1915a394d2ace3393R43

**Comment by westurner** [comment]
(I would've just ``EXTEND``-ed from this container if I had been aware of it.)

Are there any plans to offer e.g. a CentOS version w/ selinux support?

**Comment by westurner** [comment]
If you ever decide to offer alternate OS containers (e.g. 14.04, 16.04, CentOS 7), these may be of use:

* [docker/Dockerfile.base.jinja](https://github.com/schemaorg/schemaorg/pull/1007/files#diff-1e41f96be24497d4601ba62225fe5495)
* [docker/_build.py](https://github.com/schemaorg/schemaorg/pull/1007/files#diff-6ccbd97a3aa9d171a644507df2d750ac) 

Issues with these:

* ``ENV`` variables are configurable but slow
* Rather than re-cloning the app, from ``./docker/Dockerfile.osname-ver``, it would be easier to set ``CWD`` to ``./docker/..``
  * 1. so that it's unnecessary to clone the source repo in order to have multiple Dockefiles w/ various OSes
  * 2. so that there aren't so many files in the project root
  * [ ] is there a way to specify ``CWD`` as ``./docker/..`` on the commandline? @jpetazzo
    * file an issue for: https://twitter.com/westurner/status/701906680091553792

**Comment by jonparrott** [comment]
We are standardizing on Debian Jessie as the base for all officially-supported App Engine Flexible runtimes. If you'd like to use CentOS or another base, you're free to use a custom runtime. The compat libraries here may or may not work in alternative operating systems.

I've assigned @bryanmau1 to tend to the issue of the process running as root. It's likely that we don't run the container as privileged in the VM, so 'root in the container' is likely a different user than 'root in the vm'. It's also likely that any sort of decision on this will need to be propagated across all of our runtimes for consistency.

**Comment by jonparrott** [comment]
After internal discussion, we will not be adding this to our base images. How we run the container in the vm is not part of the runtime contract, and we also don't want to add a non-universal restriction to the base image.

If you want to run your containers as non-root, you're welcome to create a custom runtime and add this declaration explicitly. (& if you're truly paranoid about security, it's likely you'll be building your own images anyway).

**Comment by jonparrott** [comment]
Thanks for bringing this up @westurner.

**Comment by westurner** [comment]
Well, thanks for the feedback. These may be of use to you:

* https://docs.docker.com/engine/security/apparmor/
* https://wiki.debian.org/SELinux/Setup
* https://access.redhat.com/documentation/en/red-hat-enterprise-linux-atomic-host/7/container-security-guide/chapter-6-docker-selinux-security-policy
* https://apps.fedoraproject.org/packages/docker-selinux/
